name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Run tests
        run: |
          crystal build main.c
          crystal spec
      - name: Build executable
        run: shards build --release
      - name: Run executable (help)
        run: |
          if [ -f bin/mmistat ]; then bin/mmistat --help; fi
      - uses: actions/upload-artifact@v4
        with:
          name: mmistat-${{ matrix.os }}
          path: bin/${{ matrix.os == 'windows' && 'mmistat.exe' || 'mmistat' }}
